# .github/workflows/ci.yml
name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code with black
        run: |
          pip install black
          black --check .

      - name: Type check with mypy
        run: |
          pip install mypy
          mypy .

      - name: Train model
        run: |
          python model/train.py

      - name: Run tests with coverage
        run: |
          pip install pytest-cov
          pytest --cov=api --cov=model --cov-report=term-missing
